server:
  context-path: /aysa
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 18!Padikal18000
    keyStoreType: PKCS12
    keyAlias: tomcat


spring:
  datasource:
    url: jdbc:postgresql://ayyappasamaajdb.cnexos2balwj.us-west-2.rds.amazonaws.com:5432/aysa_db
    username: aysa_user
    password: 18!Padikal18000
    platform: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    format_sql: true
    sql_comments: true
    hibernate:
      ddl-auto: validate